name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        run: |
          git clone --depth 1 ${{ github.server_url }}/${{ github.repository }} .
          git fetch origin ${{ github.sha }}
          git checkout ${{ github.sha }}

      - name: Install mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run CI checks
        run: |
          mise install
          mise run ci
